# Copyright 2026 The IREE Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("//build_tools/testing:build_defs.bzl", "iree_execution_test_suite")
load("//runtime/build_tools/bazel:cc.bzl", "iree_runtime_cc_binary")

package(
    default_visibility = ["//visibility:private"],
    features = ["layering_check"],
    licenses = ["notice"],
)

iree_runtime_cc_binary(
    name = "vm-as",
    srcs = ["vm-as.c"],
    visibility = ["//tools:__pkg__"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/tooling:flags",
        "//runtime/src/iree/io:file_handle",
        "//runtime/src/iree/io:stream",
        "//runtime/src/iree/vm/bytecode:assembler",
    ],
)

iree_runtime_cc_binary(
    name = "vm-dis",
    srcs = ["vm-dis.c"],
    visibility = ["//tools:__pkg__"],
    deps = [
        "//runtime/src/iree/base",
        "//runtime/src/iree/base/tooling:flags",
        "//runtime/src/iree/io:file_handle",
        "//runtime/src/iree/io:stream",
        "//runtime/src/iree/vm/bytecode:disassembler",
    ],
)

iree_execution_test_suite(
    name = "execution_test",
    data = ["//runtime/src/iree/vm/bytecode:testdata/launch_config.vmasm"],
    manifests = ["vm-tools.test.json"],
    tools = {
        "vm-as": ":vm-as",
        "vm-dis": ":vm-dis",
    },
)
